import { useCallback, useContext, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { FaUser,FaPhone,FaMapMarkerAlt,FaCity,FaHashtag,FaCheckCircle,FaPlus,FaIdBadge,FaShieldAlt,FaTimes,FaCamera,FaTrash,FaEdit,FaSave,FaEnvelope,FaBriefcase,FaStar,FaMapPin,FaCompass,FaHome,FaChevronRight,FaLock } from "react-icons/fa";
import { getMyProfile,updateMyProfile,uploadProfilePicture,removeProfilePicture,getMyAddresses,addAddress,updateAddress,deleteAddress } from "../api/profileApi";
import { AuthContext } from "../context/AuthContext";
import toast from "react-hot-toast";
import "../styles/profile-settings.css";

const EMPTY_ADDRESS={city:"",area:"",pincode:""};

const Modal=({open,title,subtitle,icon,children,onClose})=>{
  if(!open)return null;
  return createPortal(<div className="pfx-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}>
    <div className="pfx-modal" role="dialog" aria-modal="true">
      <div className="pfx-modal-head"><div className="pfx-modal-icon">{icon}</div><div className="pfx-modal-heading"><h3>{title}</h3><p>{subtitle}</p></div><button className="pfx-modal-close" type="button" onClick={onClose}><FaTimes/></button></div>
      {children}
    </div>
  </div>,document.body);
};

const ProfileSettings=()=>{
 const {user,login}=useContext(AuthContext),fileInputRef=useRef(null);
 const [profile,setProfile]=useState(null),[profileForm,setProfileForm]=useState({fullName:"",phone:""}),[addresses,setAddresses]=useState([]);
 const [loadingAddresses,setLoadingAddresses]=useState(true),[savingProfile,setSavingProfile]=useState(false),[pictureBusy,setPictureBusy]=useState(false),[addressBusy,setAddressBusy]=useState(false),[deletingAddressId,setDeletingAddressId]=useState(null);
 const [profileModal,setProfileModal]=useState(false),[addressModal,setAddressModal]=useState(false),[pictureModal,setPictureModal]=useState(false),[editingAddressId,setEditingAddressId]=useState(null),[addressForm,setAddressForm]=useState(EMPTY_ADDRESS);
 const role=profile?.role||user?.role;
 const roleLabel=useMemo(()=>role==="PROVIDER"?"Service Provider":role==="ADMIN"?"Administrator":"User",[role]);
 const initials=(profile?.fullName||user?.fullName||"U").trim().charAt(0).toUpperCase();
 const resolveImage=path=>{if(!path)return "";if(/^https?:\/\//i.test(path))return path;const base=(import.meta.env.VITE_API_BASE_URL||"").replace(/\/$/,"");return base+(path.startsWith("/")?"":"/")+path};
 const profileImage=resolveImage(profile?.profilePicture);
 const syncAuthUser=useCallback(data=>login({...user,id:data.userId,fullName:data.fullName,phone:data.phone,email:data.email,role:data.role,providerId:data.provider?.providerId??user?.providerId,profilePicture:data.profilePicture||null}),[login,user]);
 const loadProfile=useCallback(async()=>{try{const r=await getMyProfile();setProfile(r.data);setProfileForm({fullName:r.data.fullName||"",phone:r.data.phone||""})}catch(e){toast.error(e?.response?.data?.message||"Unable to load your profile.")}},[]);
 const loadAddresses=useCallback(async()=>{if(!user?.id)return;try{setLoadingAddresses(true);const r=await getMyAddresses(user.id);setAddresses(r.data||[])}catch(e){toast.error(e?.response?.data?.message||"Unable to load saved addresses.")}finally{setLoadingAddresses(false)}},[user?.id]);
 useEffect(()=>{loadProfile()},[loadProfile]);useEffect(()=>{loadAddresses()},[loadAddresses]);
 useEffect(()=>{const k=e=>{if(e.key==="Escape"){setProfileModal(false);setAddressModal(false);setPictureModal(false)}};window.addEventListener("keydown",k);return()=>window.removeEventListener("keydown",k)},[]);
 const openProfileEdit=()=>{setProfileForm({fullName:profile?.fullName||"",phone:profile?.phone||""});setProfileModal(true)};
 const saveProfile=async()=>{const fullName=profileForm.fullName.trim(),phone=profileForm.phone.trim();if(!fullName)return toast.error("Full name is required.");if(!/^[6-9]\d{9}$/.test(phone))return toast.error("Enter a valid 10-digit Indian mobile number.");try{setSavingProfile(true);const r=await updateMyProfile({fullName,phone});setProfile(r.data);setProfileForm({fullName:r.data.fullName||"",phone:r.data.phone||""});syncAuthUser(r.data);setProfileModal(false);toast.success("Profile updated successfully.")}catch(e){toast.error(e?.response?.data?.message||"Unable to update your profile.")}finally{setSavingProfile(false)}};
 const handlePictureChange=async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type))return toast.error("Only JPG, PNG and WEBP images are allowed.");if(file.size>2*1024*1024)return toast.error("Profile picture must be 2 MB or smaller.");try{setPictureBusy(true);const r=await uploadProfilePicture(file);setProfile(r.data);syncAuthUser(r.data);setPictureModal(false);toast.success("Profile picture updated.")}catch(err){toast.error(err?.response?.data?.message||"Unable to update your profile picture.")}finally{setPictureBusy(false)}};
 const handleRemovePicture=async()=>{if(!profile?.profilePicture)return;try{setPictureBusy(true);const r=await removeProfilePicture();setProfile(r.data);syncAuthUser(r.data);setPictureModal(false);toast.success("Profile picture removed.")}catch(e){toast.error(e?.response?.data?.message||"Unable to remove your profile picture.")}finally{setPictureBusy(false)}};
 const openAddAddress=()=>{setEditingAddressId(null);setAddressForm(EMPTY_ADDRESS);setAddressModal(true)};
 const openEditAddress=a=>{setEditingAddressId(a.id);setAddressForm({city:a.city||"",area:a.area||"",pincode:a.pincode||""});setAddressModal(true)};
 const saveAddress=async()=>{const p={city:addressForm.city.trim(),area:addressForm.area.trim(),pincode:addressForm.pincode.trim()};if(!p.city||!p.area||!/^\d{6}$/.test(p.pincode))return toast.error("Enter city, area and a valid 6-digit pincode.");try{setAddressBusy(true);if(editingAddressId){await updateAddress(editingAddressId,p);toast.success("Address updated successfully.")}else{await addAddress(user.id,p);toast.success("Address added successfully.")}setAddressModal(false);setEditingAddressId(null);setAddressForm(EMPTY_ADDRESS);await loadAddresses()}catch(e){toast.error(e?.response?.data?.message||"Unable to save the address.")}finally{setAddressBusy(false)}};
 const handleDeleteAddress=async a=>{if(!window.confirm(`Remove ${a.area}, ${a.city} from your saved addresses?`))return;try{setDeletingAddressId(a.id);await deleteAddress(a.id);toast.success("Address removed successfully.");await loadAddresses()}catch(e){toast.error(e?.response?.data?.message||"Unable to remove the address.")}finally{setDeletingAddressId(null)}};
 if(!profile)return <div className="pfx-page"><div className="pfx-shell"><div className="pfx-loading"><div className="pfx-loading-avatar"/><div><span/><span/><span/></div></div></div></div>;
 return <div className="pfx-page"><div className="pfx-shell">
  <header className="pfx-header"><div><span className="pfx-eyebrow">ACCOUNT CENTER</span><h1>Profile & Settings</h1><p>Manage your identity, contact details and saved service locations.</p></div><div className="pfx-header-status"><span className="pfx-live-dot"/> Account active</div></header>
  <section className="pfx-profile-hero"><div className="pfx-hero-glow"/><div className="pfx-hero-main">
   <button className="pfx-avatar-button" type="button" onClick={()=>setPictureModal(true)}><div className="pfx-avatar">{profileImage?<img src={profileImage} alt="Profile"/>:<span>{initials}</span>}</div><span className="pfx-camera"><FaCamera/></span></button>
   <div className="pfx-identity"><h2>{profile.fullName||"Fixly User"}</h2><p><FaEnvelope/>{profile.email}</p><div className="pfx-badges"><span className="pfx-role-badge"><FaShieldAlt/>{roleLabel}</span><span className="pfx-verified"><FaCheckCircle/> Verified account</span></div></div>
  </div><div className="pfx-hero-actions"><button className="pfx-light-btn" onClick={()=>setPictureModal(true)}><FaCamera/> Photo</button><button className="pfx-light-btn" onClick={openProfileEdit}><FaEdit/> Edit profile</button></div></section>

  <section className="pfx-grid"><article className="pfx-card"><div className="pfx-card-head"><div className="pfx-section-icon blue"><FaIdBadge/></div><div><span className="pfx-card-kicker">PERSONAL</span><h3>Personal information</h3><p>Your account details and login identity.</p></div><button className="pfx-icon-btn" onClick={openProfileEdit}><FaEdit/></button></div><div className="pfx-info-list">
   <div className="pfx-info-row"><span><FaUser/> Full name</span><strong>{profile.fullName||"—"}</strong></div><div className="pfx-info-row"><span><FaPhone/> Phone</span><strong>{profile.phone||"—"}</strong></div><div className="pfx-info-row"><span><FaEnvelope/> Email</span><strong>{profile.email||"—"}</strong></div>
  </div><button className="pfx-card-link" onClick={openProfileEdit}>Update personal details <FaChevronRight/></button></article>
  {role==="PROVIDER"&&profile.provider&&<article className="pfx-card"><div className="pfx-card-head"><div className="pfx-section-icon amber"><FaBriefcase/></div><div><span className="pfx-card-kicker">PROFESSIONAL</span><h3>Provider profile</h3><p>Your professional account snapshot.</p></div><span className="pfx-status-badge">{profile.provider.status}</span></div><div className="pfx-provider-stats">
   <div><strong>{profile.provider.category||"—"}</strong><span>Category</span></div><div><strong>{profile.provider.experienceYears??0} yrs</strong><span>Experience</span></div><div><strong>{Number(profile.provider.rating||0).toFixed(1)} <FaStar/></strong><span>Rating</span></div><div><strong>{profile.provider.available?"Available":"Offline"}</strong><span>Availability</span></div>
  </div></article>}</section>

  <section className="pfx-card pfx-address-section"><div className="pfx-card-head"><div className="pfx-section-icon violet"><FaMapPin/></div><div><span className="pfx-card-kicker">LOCATIONS</span><h3>Saved addresses</h3><p>Use saved locations for faster service booking.</p></div><button className="pfx-primary-btn" onClick={openAddAddress}><FaPlus/> Add address</button></div>
   {loadingAddresses?<div className="pfx-address-loading"><span/><span/><span/></div>:addresses.length?<div className="pfx-address-grid">{addresses.map((a,i)=><div className={`pfx-address-card ${i===0?"primary":""}`} key={a.id??i}><div className="pfx-address-top"><div className="pfx-address-icon"><FaHome/></div>{i===0&&<span className="pfx-primary-label">Primary</span>}</div><h4>{a.area}, {a.city}</h4><p><FaMapMarkerAlt/>{a.pincode}</p><div className="pfx-address-actions"><button onClick={()=>openEditAddress(a)}><FaEdit/> Edit</button><button className="danger" disabled={deletingAddressId===a.id} onClick={()=>handleDeleteAddress(a)}><FaTrash/>{deletingAddressId===a.id?"Removing...":"Remove"}</button></div></div>)}</div>:<div className="pfx-empty"><div><FaCompass/></div><h4>No saved addresses</h4><p>Add your first service location to make booking faster.</p><button className="pfx-primary-btn" onClick={openAddAddress}><FaPlus/> Add first address</button></div>}
  </section>
  <div className="pfx-security-note"><FaLock/><span><strong>Your account is protected.</strong> Email remains your login identity and cannot be changed here.</span></div>
 </div>
 <Modal open={profileModal} title="Update profile" subtitle="Keep your contact details current." icon={<FaUser/>} onClose={()=>setProfileModal(false)}><div className="pfx-modal-body"><div className="pfx-modal-form-grid"><label className="pfx-field"><span>Full name</span><div><FaUser/><input value={profileForm.fullName} maxLength={100} onChange={e=>setProfileForm({...profileForm,fullName:e.target.value})} placeholder="Your full name"/></div></label><label className="pfx-field"><span>Phone number</span><div><FaPhone/><input value={profileForm.phone} maxLength={10} inputMode="numeric" onChange={e=>setProfileForm({...profileForm,phone:e.target.value.replace(/\D/g,"")})} placeholder="10-digit mobile number"/></div></label></div><div className="pfx-readonly"><FaEnvelope/><div><strong>{profile.email}</strong><span>Login email cannot be edited from profile settings.</span></div></div><div className="pfx-modal-actions"><button className="pfx-secondary-btn" onClick={()=>setProfileModal(false)} disabled={savingProfile}><FaTimes/> Cancel</button><button className="pfx-primary-btn" onClick={saveProfile} disabled={savingProfile}><FaSave/>{savingProfile?"Saving...":"Save changes"}</button></div></div></Modal>
 <Modal open={addressModal} title={editingAddressId?"Edit address":"Add new address"} subtitle={editingAddressId?"Update this saved service location.":"Add a location for faster bookings."} icon={<FaMapPin/>} onClose={()=>setAddressModal(false)}><div className="pfx-modal-body"><div className="pfx-modal-form-grid"><label className="pfx-field"><span>City</span><div><FaCity/><input value={addressForm.city} maxLength={100} onChange={e=>setAddressForm({...addressForm,city:e.target.value})} placeholder="e.g. New Delhi"/></div></label><label className="pfx-field"><span>Area</span><div><FaMapMarkerAlt/><input value={addressForm.area} maxLength={150} onChange={e=>setAddressForm({...addressForm,area:e.target.value})} placeholder="e.g. Dwarka"/></div></label><label className="pfx-field"><span>Pincode</span><div><FaHashtag/><input value={addressForm.pincode} maxLength={6} inputMode="numeric" onChange={e=>setAddressForm({...addressForm,pincode:e.target.value.replace(/\D/g,"")})} placeholder="110075"/></div></label></div><div className="pfx-modal-actions"><button className="pfx-secondary-btn" onClick={()=>setAddressModal(false)} disabled={addressBusy}><FaTimes/> Cancel</button><button className="pfx-primary-btn" onClick={saveAddress} disabled={addressBusy}><FaSave/>{addressBusy?"Saving...":editingAddressId?"Update address":"Save address"}</button></div></div></Modal>
 <Modal open={pictureModal} title="Profile picture" subtitle="Choose a clear photo for your Fixly account." icon={<FaCamera/>} onClose={()=>setPictureModal(false)}><div className="pfx-photo-modal"><div className="pfx-photo-preview">{profileImage?<img src={profileImage} alt="Profile preview"/>:<span>{initials}</span>}</div><p>JPG, PNG or WEBP · Maximum 2 MB</p><input ref={fileInputRef} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={handlePictureChange}/><div className="pfx-photo-actions"><button className="pfx-primary-btn" onClick={()=>fileInputRef.current?.click()} disabled={pictureBusy}><FaCamera/>{pictureBusy?"Uploading...":profileImage?"Change photo":"Upload photo"}</button>{profileImage&&<button className="pfx-secondary-btn pfx-danger-btn" onClick={handleRemovePicture} disabled={pictureBusy}><FaTrash/> Remove photo</button>}</div></div></Modal>
 </div>;
};
export default ProfileSettings;